Fix error in fetching managers
Error: First time fetching managers is good
however, error in opening the form a
second time

Fixed by making create project screen
the ChangeNotifierProvider
and removed from the MaterialApp widget